CREATE TABLE USUARIO
(
    USERID VARCHAR(25) NOT NULL ,
    EMAIL VARCHAR(30) NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
    DATAHORACRIACAO DATETIME2 NOT NULL,
    DATAHORACONFIRMACAO DATETIME2,
    CONSTRAINT PK_USUARIO PRIMARY KEY(USERID),
    CONSTRAINT UNIQUE_EMAIL UNIQUE(EMAIL)
);


CREATE TABLE PARTIDA
(
    PARTIDAID INT IDENTITY(1,1) NOT NULL,
    USERID VARCHAR(25) NOT NULL,
    DATAHORAINICIO DATETIME2 NOT NULL,
    RESULTADO VARCHAR(4),
    DATAHORAFIM DATETIME2,
    CONSTRAINT PK_NUMERO_PARTIDA PRIMARY KEY(PARTIDAID),
    CONSTRAINT FK_USERNAME_PARTIDA FOREIGN KEY(USERID) REFERENCES USUARIO(USERID)

);

CREATE TABLE PARTIDADETALHE
(
    NUMEROROUND INT NOT NULL,
    PARTIDAID INT NOT NULL,
    ESCOLHAJOGADOR VARCHAR(7) NOT NULL,
    ESCOLHACOMPUTADOR VARCHAR(7) NOT NULL,
    RESULTADO VARCHAR(4) NOT NULL,
    CONSTRAINT PK_PARTIDADETALHE PRIMARY KEY (PARTIDAID, NUMEROROUND),
    CONSTRAINT FK_PARTIDADETALHE FOREIGN KEY(PARTIDAID) REFERENCES PARTIDA(PARTIDAID)
);
